title: AkuTrust
description: >
   Platform berbasis AI yang dirancang untuk meningkatkan transparansi dan efisiensi dalam pengelolaan dana penataan dan rehabilitasi konstruksi daerah.
theme: jekyll-theme-cayman
